### ISSUE TITLE
Broken documentation website

### ISSUE THREAD

**Issue by apaikan** [robotology/robot-testing-framework#104]
Hi guys,
  is there any plan to update (bring it back) the missing documentation website? 
this link is broken: http://robotology.github.io/robot-testing/index.html

**Comment by Nicogene** [comment]
Hi Ali,

the website url has changed in:

http://robotology.github.io/robot-testing-framework/index.html

This is due to the renaming of the repo.
I changed it in the description, if you find another places where there is the old url let me know and I will change it.

**Comment by apaikan** [comment]
Hi Nicolo, 
First of all it is nice to here from you :)

Thanks for the update. 

Cheers,
 Ali
